server:
  port: 8080
spring:
  datasource:
    username: root
    password: Abcd1234
    url: jdbc:mysql://localhost:3306/crud?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

